name: Go func tests

env:
  cc_id: "dc01d78c839fd71c0657b8fea93c8d92a79b378bea0ad571181cba0364cc18ba"
  code_dir: "mainpkg"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ env.cc_id }}
        with:
          coverageCommand: go test -v ./... -coverprofile=c.out
          debug: true
          prefix: github.com/Ryo-not-rio/grapi