name: Go func tests

env:
  cc_id: "dc01d78c839fd71c0657b8fea93c8d92a79b378bea0ad571181cba0364cc18ba"
  code_dir: "mainpkg"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./... -coverprofile=c.out

      - name: publish to code climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ env.cc_id }}
        with:
          debug: true
          prefix: github.com/Ryo-not-rio/wuzz

      - name: publish to code cov
        uses: codecov/codecov-action@v2
        with:
          files: ./c.out